# Generated by Django 5.2.3 on 2025-07-11 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pitched', models.BooleanField(blank=True, null=True)),
                ('is_pitched_at', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, null=True)),
                ('address', models.CharField(blank=True, null=True)),
                ('city', models.CharField(blank=True, null=True)),
                ('state', models.CharField(blank=True, null=True)),
                ('country', models.CharField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
